### ISSUE TITLE
Refactor messaging interface

### ISSUE THREAD

**Issue by ChShersh** [kowainik/life-sync#20]
I propose the following refactoring to messaging interface.

1. Introduce `Severity`: `data Severity = Error | Warning | Skip ...`
2. Have only single function `message` like: `message :: Severity -> Text -> IO ()`
3. Add `messageExit` function which calls `exitFailure` after calling `message`

**Comment by vrom911** [comment]
I don't see a lot of benefits of this one. Could you please elaborate?

From my point of view it's better to use ready logging library instead of writing new one in the project which  is not about the logging. We could spend a lot of time on implementing all this stuff (even messaging took some time which was just wasting of time) so better to have something ready as I see you could want much more stuff to be implemented in `Message` module.

**Comment by ChShersh** [comment]
@vrom911 That's valid point. I agree that we might want a lot of features from pretty message printing library. I also agree that it's better to have/use proper solution instead of wasting time on patching our current ad-hoc solution.
