### ISSUE TITLE
Revive life-sync repo (cleanup, update, etc.)

### ISSUE THREAD

**Issue by chshersh** [kowainik/life-sync#65]
- [x] Migrate to latest GHC-8.8
- [x] Update `stack` snapshot
- [x] Use best-practices `.travis.yml` for both `cabal` and `stack`
- [x] Migrate to the latest `relude`, add HLint check, fix HLint warnings
- [x] Migrate to the latest `tomland`
- [ ] Use `shellmet`
- [x] Use latest warnings list
- [x] Cleanup default extensions
- [x] Update `.cabal` file metadata
- [x] Use common stanzas
- [x] Update `.gitignore`

Anything else needs to be done?

**Comment by Nimor111** [comment]
Hey, since this project is something i've been looking for lately, I'd like to work on reviving it. :) Since most of these seem like small changes, could they be done in a single PR? Or maybe make a division along the lines of:

* Build-tool and compiler updates ( with the build tool files updated )
* Library version upgrades 
* CI update

Each being a separate PR?
